on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Atualização do código
      uses: actions/checkout@v2

    - name: Atualizar Node Js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Instalar dependências
      run: npm install
      working-directory: Cliente

    - name: Instalar outras dependências
      run:  npm install --save-dev @babel/plugin-proposal-private-property-in-object
      working-directory: Cliente
      
    - name: Build do projeto
      run: |
        cd Cliente
        CI=false npm run build

    - name: Gerar artefato Github com os arquivos de build
      uses: actions/upload-artifact@v4
      with:
        name: build-react-app
        path: build/**/*

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Recuperar jars
      uses: actions/download-artifact@v4  # essa action promove o download de um ou mais arquivos de uma pasta temporária do github actions
      with:
        name: aplicacao # nome do arquivo ou conjunto de arquivos que queremos recuperar
        path: ./ # diretório da VM de execução do workflow onde os arquivos recuperados ficarão
        
    - name: Verificar estrutura de diretórios
      run: ls -la
      
    - name: Compactar artefato
      run: |
        cd Cliente
        tar -czf Cliente.tar.gz build   

    - name: Deploy para EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: Cliente.tar.gz
        target: /var/www/Cliente/

    - name: Criar arquivo .pem a partir da variável DEPLOY_KEY e fazer o chmod 400 nele
      id: geracao-arquivo-pem # o id é opcional, mas é bom para fins de log
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" >> $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
        chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
      

    # Step 8: Conectar na EC2 e reiniciar o servidor
    - name: Reiniciar aplicação
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /var/www/Cliente/
          tar -xzf Cliente.tar.gz
          rm -rf Cliente.tar.gz
          # Comando para reiniciar seu servidor, por exemplo:
          pm2 restart all
